from pathlib import Path
from html import escape
import tomllib

ROOT=Path(__file__).parent
OUT=ROOT/'dist'
REPO='https://github.com/GiovanniCaiazzo01/Ghostty-wall'
PACKAGE=tomllib.loads((ROOT.parent/'Cargo.toml').read_text())['package']
VERSION=PACKAGE['version']
ICONS={
'arrow':'<path d="M7 17 17 7M7 7h10v10"/>',
'right':'<path d="M4 12h16m-6-6 6 6-6 6"/>',
'chevron':'<path d="m9 5 7 7-7 7"/>',
'book':'<path d="M12 5v15M12 5C8 2 4 3 2 4v15c3-1 7-1 10 1 3-2 7-2 10-1V4c-2-1-6-2-10 1Z"/>',
'download':'<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>',
'bolt':'<path d="m13 2-9 12h7l-1 8 10-12h-7l1-8Z"/>',
'code':'<path d="m7 7-5 5 5 5m10-10 5 5-5 5m-4-13-2 20"/>',
'layers':'<path d="m12 3 10 5-10 5L2 8l10-5Zm-10 9 10 5 10-5M2 16l10 5 10-5"/>',
'image':'<rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1"/><path d="m21 15-6-6L3 21"/>',
'palette':'<path d="M12 3a9 9 0 1 0 0 18h1a2 2 0 0 0 0-4 2 2 0 0 1 0-4h4a4 4 0 0 0 4-4c0-4-5-6-9-6Z"/><path d="M7 8h.01M11 6h.01M16 7h.01M5 12h.01"/>',
'terminal':'<rect x="2" y="3" width="20" height="18" rx="3"/><path d="m6 8 4 4-4 4m7 0h5"/>',
'settings':'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="15" cy="17" r="3"/>',
'life':'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="4"/><path d="m5.5 5.5 3.7 3.7m5.6 5.6 3.7 3.7m0-13-3.7 3.7m-5.6 5.6-3.7 3.7"/>',
'github':'<path d="M9 19c-4 1-4-2-6-2m12 5v-4a3 3 0 0 0-.8-2.3c2.7-.3 5.6-1.3 5.6-6a4.7 4.7 0 0 0-1.3-3.3 4.3 4.3 0 0 0-.1-3.3s-1-.3-3.4 1.3a11.7 11.7 0 0 0-6 0C6.6 2.8 5.6 3.1 5.6 3.1a4.3 4.3 0 0 0-.1 3.3 4.7 4.7 0 0 0-1.3 3.3c0 4.7 2.9 5.7 5.6 6A3 3 0 0 0 9 18v4"/>',
'copy':'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h3"/>',
'check':'<path d="m5 12 4 4L19 6"/>',
'menu':'<path d="M4 6h16M4 12h16M4 18h16"/>',
'info':'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v.01"/>',
'rewind':'<path d="M3 10h6M3 10V4m0 6a9 9 0 1 1 1 8"/>',
'heart':'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>'}
def icon(name): return f'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.55" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">{ICONS[name]}</svg>'
def code(text,label='Terminal',lang='shell'):
    text=text.strip('\n')
    lines=[]
    for line in text.splitlines():
        s=escape(line)
        if lang=='toml':
            if line.startswith('['): s=f'<span class="syn-section">{s}</span>'
            elif '=' in line:
                k,v=s.split('=',1); s=f'<span class="syn-key">{k}</span>=<span class="syn-string">{v}</span>'
        elif line.startswith('#'): s=f'<span class="syn-comment">{s}</span>'
        elif line.startswith('ghostty-wall'): s='<span class="syn-command">ghostty-wall</span>'+s[len('ghostty-wall'):]
        elif line.startswith('cargo'): s='<span class="syn-command">cargo</span>'+s[5:]
        lines.append(s)
    return f'<div class="code-block"><div class="code-header"><span>{icon("terminal" if lang=="shell" else "code")}{escape(label)}</span><button class="copy-button" type="button" aria-label="Copy {escape(label)} code">{icon("copy")}<span>Copy</span></button></div><pre tabindex="0"><code>'+ '\n'.join(lines)+'</code></pre></div>'
def note(text,title='Good to know'): return f'<aside class="callout">{icon("info")}<div><strong>{title}</strong><p>{text}</p></div></aside>'
def section(id,title,body): return f'<section id="{id}" class="doc-section"><h2><a href="#{id}">{title}<span aria-hidden="true">#</span></a></h2>{body}</section>'
def table(headers,rows):
    return '<div class="table-wrap"><table><thead><tr>'+''.join(f'<th>{h}</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join(f'<td>{c}</td>' for c in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def card(page,title,description,ico): return f'<a class="doc-card" href="/{page}/"><div class="card-top">{icon(ico)}{icon("right")}</div><h3>{title}</h3><p>{description}</p></a>'
def path(page): return '/' if page=='overview' else '/'+page+'/'

profile='''schema_version = 1

[wallpaper]
mode = "source"
source = "wallpapers"
selection = "path"
path = "city/night.png"
fit = "cover"
position = "center"
opacity = 0.05 # wallpaper strength; not terminal transparency

[colors]
mode = "generated"

[terminal]
font_size = 13.5
background_opacity = 0.94
cursor_style = "bar"'''
source='''[sources.wallpapers]
kind = "local-directory"
path = "~/Pictures/wallpapers"'''
seed='000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f'
pages={}
def page(key,title,desc,group,body,toc): pages[key]=dict(title=title,desc=desc,group=group,body=body,toc=toc)

palette=['#0d1535','#ff9255','#79efcf','#ffc861','#4265ce','#8670ff','#50c4c5','#d3e2ff','#2d3f7c','#ffb078','#a3ffe2','#ffdb95','#799bff','#b8a5ff','#8de9e0','#f1f6ff']
demo=f'''<figure class="terminal-demo"><div class="demo-top"><div class="window-dots"><i></i><i></i><i></i></div><span>welcome to your new terminal</span><span class="demo-shell">ghostty</span></div><div class="demo-body"><img src="/assets/welcome.png" alt="The bundled Ghostty Wall welcome wallpaper" width="1672" height="941"><div class="demo-shade"></div><div class="demo-code"><span class="demo-comment"># A little more you. Every time you open a terminal.</span><div><span class="prompt">❯</span> ghostty-wall apply welcome</div><div class="demo-result"># Wallpaper + generated terminal colors</div><div class="demo-prompt"><span class="prompt">❯</span> <span class="cursor"></span></div></div><div class="demo-tag">BUNDLED WELCOME WALLPAPER</div></div><figcaption><span>Wallpaper → palette → environment</span><div class="swatches" aria-label="Illustrative terminal color palette">{''.join(f'<i style="background:{c}"></i>' for c in palette)}</div></figcaption></figure>'''
page('overview','Make Ghostty<br><em>your own.</em>','Wallpapers, colors, and visual settings. One reusable profile.<br>A small Rust CLI for a terminal that feels like home.','Get started',
 '''<div class="overview-actions"><a class="button primary" href="/installation/">Install Ghostty Wall '''+icon('right')+f'''</a><a class="text-link" href="{REPO}">View on GitHub {icon('arrow')}</a></div><div class="support-line"><span>Linux x86_64 <b>stable</b></span><span>macOS <b class="experimental">experimental</b></span><span>MIT licensed</span></div>'''+demo+
 section('start-here','A good place to start', '<div class="card-grid">'+card('quick-start','Your first environment','Go from a fresh install to your first wallpaper in a few commands.','bolt')+card('profiles','Build your own profile','Bring your wallpapers. Make the colors and settings yours.','layers')+'</div>')+
 section('why-ghostty-wall','Less configuration. More character.',f'''<div class="feature-list"><div>{icon('palette')}<div><h3>Colors that belong together</h3><p>Generate a complete terminal palette from your wallpaper, use a Ghostty theme, or set every color yourself.</p></div></div><div>{icon('code')}<div><h3>Create, edit, preview, choose</h3><p>Generate a wallpaper or pick your image, customize a visual draft, then Save and use. The internal sample is not live Ghostty reload; selection never activates a profile.</p></div></div><div>{icon('rewind')}<div><h3>A way back, built in</h3><p>Return to a saved environment with <code>previous</code>, even if its original wallpaper source is gone.</p></div></div></div>''')+
 section('how-it-works','A recipe. A result. A record.', '''<div class="concept-grid"><div><span class="step-kicker">01 / INTENT</span><h3>Profile</h3><p>The saved recipe for your look. Create and edit it without writing TOML.</p></div><div><span class="step-kicker">02 / RESULT</span><h3>Environment</h3><p>An immutable snapshot of resolved images and settings.</p></div><div><span class="step-kicker">03 / HISTORY</span><h3>Activation</h3><p>A durable record of the environment you applied.</p></div></div>'''),
 [('start-here','Start here'),('why-ghostty-wall','Why Ghostty Wall?'),('how-it-works','How it works')])

page('installation','Installation','One installation route: the curl installer for Linux x86_64.','Get started',
 section('requirements','Before you begin','<p>The curl installer is currently the <strong>only supported installation method</strong>, for <strong>Linux x86_64</strong> (<code>x86_64-unknown-linux-gnu</code>). You need Ghostty, Bash, curl, tar and sha256sum. No Rust toolchain is needed.</p><p>macOS code remains experimental, but there is no supported installer for macOS or other Linux architectures at this time. Windows is unsupported. Live draft reload and restoration remain unverified; CLI and TUI previews are internal samples.</p>')+
 section('quick-install','Install with curl',code('curl -fsSL https://raw.githubusercontent.com/GiovanniCaiazzo01/Ghostty-wall/main/scripts/install-release.sh | bash')+'<p>The installer downloads the latest stable release, verifies its SHA-256 checksum and installs into <code>~/.local/bin</code> by default. You can change the prefix with <code>INSTALL_PREFIX</code>. Initialization remains an explicit next step.</p>')+
 section('path-conflicts','Check which installation runs',code('command -v ghostty-wall\nghostty-wall --version')+'<p>The selected path should be <code>~/.local/bin/ghostty-wall</code>, or the bin directory of your custom prefix. An older Cargo or manual installation, such as <code>~/.cargo/bin/ghostty-wall</code>, can take precedence in PATH. The curl installer does not remove or upgrade copies in other directories.</p><p>If the version still looks old, check the new installation directly:</p>'+code('~/.local/bin/ghostty-wall --version\n~/.local/bin/ghostty-wall update --check')+'<p>Adjust those paths for a custom prefix. Put the new bin directory before the old one in PATH. For Fish:</p>'+code('fish_add_path --move --prepend ~/.local/bin','Fish')+'<p>For Bash or Zsh:</p>'+code('export PATH="$HOME/.local/bin:$PATH"\nhash -r','Bash / Zsh')+'<p>The Bash/Zsh change applies to the current shell; add the PATH setting to your shell startup configuration to keep it in new terminals. Recheck the selected path before initializing or updating. Your Profiles and History are unaffected.</p>')+
 section('initialize','Initialize your installation',code('ghostty-wall init')+'<p>Initialization creates the managed directory, installs the Ghostty integration hook, and adds a bundled <code>welcome</code> profile to fresh installations.</p>'+note('Use <code>ghostty-wall init --dry-run</code> to inspect the changes before writing anything. Existing profiles are not overwritten.','Preview the setup'))+
 section('update','Keep the program current',code('ghostty-wall update --check\nghostty-wall update')+'<p>This explicit command updates the curl-managed installation, including custom prefixes. It updates the executable being invoked, not another copy on PATH, and never updates Ghostty itself. Check the selected path above if an older version still runs. <code>--check</code> fetches release metadata only: it does not install or change user data. Already-current versions are a no-op; nothing updates automatically at startup.</p><p>The updater uses the version-pinned official Linux x86_64 archive, SHA-256 verification, bounded archive/platform checks and executable-version verification. The executable and <code>.ghostty-wall-release.sha256</code> are published with rollback protection.</p><p>Progress distinguishes checking, preparing, verifying and installing. Keep other installers idle. Writable installation directories with atomic-exchange support are required; missing tools, ambiguous/mismatched ownership, substituted paths and manual/unowned binaries are rejected without privilege escalation. Repair ownership using the original installer, not by deleting safeguards.</p><p>Preparation failures leave the installation untouched. Publication failures roll back binary and metadata; if rollback also fails, inspect the recovery paths in the error before retrying. This is not a crash-atomic multi-file transaction: forced termination or power loss may require recovery from <code>.ghostty-wall-update-*</code> files. Profiles, Sources, History, Environments, assets and integration are preserved. Restart Ghostty Wall after replacement; a running TUI retains its old version. See <code>ghostty-wall update --help</code>.</p>')+
 section('next-step','Make it yours','<p>You are ready to create your first Profile.</p>'+card('quick-start','Continue to quick start','Create, preview, use, and go back.','bolt')),
 [('requirements','Requirements'),('quick-install','Install with curl'),('path-conflicts','PATH conflicts'),('initialize','Initialize'),('update','Update'),('next-step','Next step')])

page('quick-start','Your first environment','Start with the bundled welcome profile. No wallpaper collection or configuration file needed.','Get started',
 section('initialize','1. Initialize Ghostty Wall','<p>Run this once after installing the CLI. Fresh installations include the welcome profile and its wallpaper.</p>'+code('ghostty-wall init'))+
 section('preview','2. Preview the result','<p>Resolve the profile and inspect its settings before applying anything. Planning does not change files.</p>'+code('ghostty-wall plan welcome'))+
 section('apply','3. Apply your profile','<p>Activate the wallpaper and its generated colors. Ghostty Wall records an activation in local history, then attempts to reload Ghostty.</p>'+code('ghostty-wall apply welcome')+note('If the terminal does not update immediately, reload Ghostty manually. A failed reload does not undo a committed activation.'))+
 section('create','4. Create your own Profile',code('ghostty-wall create night')+'<p>Choose Generate or Image, review the wallpaper and readable colors, then Save. Generated wallpapers stay fixed unless you explicitly choose Another variant before saving. Use now activates it; Not now keeps it saved without changing Ghostty. Cancelling before Save leaves no partial Profile.</p>')+
 section('browse','5. Customize and manage',code('ghostty-wall edit night\nghostty-wall tui')+'<p>Edit Wallpaper, Colors and Terminal controls in a visual draft. Save and use requires confirmation; Esc/q discards the draft. The management center offers Create, Edit, Delete and Use, with an active marker and an internal terminal-like sample. Moving selection never applies.</p>')+
 section('go-back','Return to a previous look','<p>Once there is an earlier environment in your history, restore it with:</p>'+code('ghostty-wall previous')+'<p>The saved environment and image are restored from local storage. The original source does not need to be available.</p>')+
 '<div class="card-grid">'+card('profiles','Create a profile','Use your own wallpaper and visual settings.','layers')+card('commands','Explore the commands','The complete CLI reference, in one place.','terminal')+'</div>',
 [('initialize','Initialize'),('preview','Preview'),('apply','Apply'),('create','Create'),('browse','Customize'),('go-back','Go back')])

page('profiles','Create, edit & delete profiles','Choose a wallpaper, customize a draft, then decide whether to use it. No internal files to edit.','Guides',
 section('create','Create without TOML',code('ghostty-wall create\nghostty-wall create night')+'<p>Supply an id to skip that prompt, or choose one interactively. IDs are lowercase; an existing id is an error, never an overwrite. Choose Generate for a stable gradient wallpaper, or Image for your PNG/JPEG. The picker starts at system Downloads/Pictures, including localized folders, and supports navigation, search and decode validation.</p><p>The original image is copied, never moved or modified. Another variant regenerates only an unsaved generated draft. Save publishes a complete Profile; Use now activates it, while Not now leaves the terminal unchanged. Cancel before Save leaves no partial Profile.</p><p>New image Profiles start at <strong>wallpaper opacity 0.05</strong> (previously 0.1), including guided CLI/TUI creation, imports, generated images, Source-based creation and newly installed Welcome. Explicit draft choices win. Existing Profiles, including omitted opacity, edits, duplicates and replay retain their semantics; no migration occurs. Terminal background opacity and text colors are not changed by this default. Lower wallpaper opacity fades toward the background: light themes can become lighter, not darker, and readability still depends on the palette.</p>')+
 section('edit','Edit a visual draft',code('ghostty-wall edit night\nghostty-wall edit')+'<p>Missing id opens a selector; a named missing Profile is an error. Tab switches Wallpaper, Colors and Terminal. Arrows adjust choices/numbers; Enter opens exact numeric entry or a color picker. In the picker, <kbd>h</kbd> accepts exact hex and <kbd>a</kbd> resets a color to Automatic. Replace image reuses the creation picker; customized colors survive wallpaper replacement.</p><p><kbd>s</kbd> opens Save and use confirmation, defaulting to Back to editor. Confirm to save once and apply; Esc/q cancels the draft without changing saved Intent or History. Declining confirmation keeps the draft. The sample is approximate, not live Ghostty reload.</p>'+note('Save, Activation and reload are distinct. A failed apply can leave a saved Profile; a failed reload does not undo an Activation. Publication uncertainty requires inspection before retrying.'))+
 section('delete','Delete safely',code('ghostty-wall delete night\nghostty-wall delete')+'<p>Confirm the named target; Enter, EOF or n cancels by default. Welcome is protected. Deleting an active Profile commits existing Welcome before removal; a failed fallback preserves the target. An older installation without Welcome fails safely rather than inventing a fallback. Inactive deletion does not change Ghostty.</p><p>Only proven-exclusive owned images are eligible for cleanup. The original image, shared or ambiguous files, Sources, History and replay assets remain. Deleting the last personal Profile leaves Welcome available. After History replay there is no active Profile hint; apply a Profile before deleting.</p>')+
 section('manage','Copy, rename and inspect',code('ghostty-wall duplicate night night-copy\nghostty-wall rename night-copy evening\nghostty-wall list\nghostty-wall preview evening\nghostty-wall history')+'<p>Rename is limited to inactive, non-Welcome Profiles. Preview and History are read-only. For direct image import, use <code>ghostty-wall new evening /path/to/image.png</code>; append <code>--apply</code> only when you want immediate activation.</p>')+
 section('compatibility','Existing Profiles and upgrades','<p>New owned-image Profiles use schema version 2, with image ownership and optional generation metadata. Existing version 1 Profiles remain readable and are not migrated just by browsing. Customizing version 1 generated colors saves version 2 Intent. Back up the entire Managed Root before downgrading; older binaries may not read new Intent or generated-color provenance.</p>')+
 section('managed-root','Advanced: configuration files','<p>On Linux, your managed root is <code>${XDG_CONFIG_HOME:-$HOME/.config}/ghostty/ghostty-wall</code>. On macOS, it is <code>~/Library/Application Support/com.mitchellh.ghostty/ghostty-wall</code>.</p><p>TOML remains an advanced interface, not a prerequisite for everyday customization.</p>'+note('Do not edit <code>current.ghostty</code>. It is generated and can be replaced on the next apply.','Keep advanced changes in Intent'))+
 section('add-source','1. Add a wallpaper source','<p>Add this section to <code>config.toml</code>. Keep the existing <code>schema_version = 1</code> and your other sources.</p>'+code(source,'config.toml','toml'))+
 section('write-profile','2. Write your profile','<p>Create <code>profiles/night.toml</code>. Its filename gives the profile its ID: <code>night</code>. Change the image path to a PNG or JPEG inside your source directory.</p>'+code(profile,'profiles/night.toml','toml'))+
 section('preview-apply','3. Preview, then apply',code('ghostty-wall plan night\nghostty-wall apply night'))+
 section('profile-rules','A few simple rules','<ul><li>IDs use lowercase letters, digits, and internal hyphens, such as <code>my-night</code>.</li><li>Profiles live directly inside <code>profiles/</code>, without subdirectories.</li><li>Wallpaper, colors, and terminal sections are optional. Omitted settings remain unmanaged.</li><li>Generated colors require a wallpaper from a source.</li></ul>'),
 [('create','Guided creation'),('edit','Visual editor'),('delete','Safe deletion'),('manage','Manage Profiles'),('compatibility','Compatibility'),('managed-root','Advanced files'),('add-source','Add a source'),('write-profile','TOML example'),('preview-apply','Preview and apply'),('profile-rules','Profile rules')])

page('wallpapers','Wallpaper sources','Keep images on your machine or pull them from a GitHub repository. Choose an exact image or a reproducible random selection.','Guides',
 section('local','Local directories',code('ghostty-wall source add wallpapers local ~/Pictures/wallpapers\nghostty-wall new night --source wallpapers --path city/night.png')+'<p>Register Sources and create Profiles without opening configuration files. Advanced equivalent:</p>'+code(source,'config.toml','toml')+'<p>Paths may be absolute, begin with <code>~/</code>, or be relative to <code>config.toml</code>. Other shell expansions are not supported. PNG and JPEG images are supported.</p>')+
 section('generated','Generate or import one image',code('ghostty-wall create night\nghostty-wall new ocean /path/to/ocean.jpg\nghostty-wall new gradient --generate '+seed)+'<p>Guided creation can generate a wallpaper or browse local images. Direct imports copy bounded, decoded PNG/JPEG bytes into owned storage; the original stays untouched. A generated wallpaper is materialized once as a PNG with its recipe, not regenerated on every apply. New Profiles get wallpaper-coordinated colors automatically.</p>')+
 section('github','GitHub repositories',code('ghostty-wall source add remote github OWNER/REPO --ref main --path wallpapers\nghostty-wall new mountain --source remote --path mountain.png')+code('''[sources.wallpapers]
kind = "github"
repository = "owner/repo"
ref = "main"
path = "wallpapers"''','config.toml','toml')+'<p>Replace <code>owner/repo</code> with your repository. Both <code>ref</code> and <code>path</code> are optional: omitting them uses the default branch and repository root.</p><p>Each plan resolves the requested branch to a commit. For authentication or higher rate limits, set <code>GITHUB_TOKEN</code> in your environment; never put a token in a profile or source file.</p>')+
 section('selection','Select an image',code('''[wallpaper]
mode = "source"
source = "wallpapers"
selection = "path"
path = "city/night.png"''','Profile · exact image','toml')+'<p>The image path is relative to the source. For random selection, use <code>selection = "random"</code> and omit <code>path</code>.</p>'+code('ghostty-wall plan night --seed '+seed+'\nghostty-wall apply night --seed '+seed)+ '<p>CLI plan/apply with random selection require a 32-byte seed, written as 64 hex digits. The TUI supplies a preview seed automatically and reuses it for Use; <code>--seed</code> overrides it. The same seed and unchanged source produce the same selection.</p>'+note('Version 1 does not include automatic timed wallpaper rotation.','Random selection'))+
 section('appearance','Control the image',table(['Setting','Supported values'],[('<code>fit</code>','<code>contain</code>, <code>cover</code>, <code>stretch</code>, <code>none</code>'),('<code>position</code>','For example, <code>center</code>, <code>top-left</code>, <code>bottom-right</code>'),('<code>opacity</code>','0 to 1; lower values fade the image toward the background, not necessarily darker'),('<code>repeat</code>','<code>true</code> or <code>false</code>')])+'<p>Omit the wallpaper section to leave it unmanaged. Use <code>mode = "none"</code> to explicitly disable the background image.</p>'),
 [('local','Local directories'),('generated','Generate or import'),('github','GitHub sources'),('selection','Image selection'),('appearance','Image settings')])

page('colors','Colors & themes','Let your wallpaper set the palette, use a familiar Ghostty theme, or take control of every color.','Guides',
 section('generated','Colors from your wallpaper',code('[colors]\nmode = "generated"','Profile · generated colors','toml')+'<p>Ghostty Wall derives the background, foreground, 16 ANSI colors, cursor, and selection colors from the selected image. Image hues tint text and ANSI colors while contrast correction keeps automatic colors readable. Monochrome images use neutral text when no hue is available. This mode requires a source wallpaper.</p>')+
 section('customize','Automatic or Customized',code('ghostty-wall edit night\nghostty-wall edit night colors.foreground e3cd7b\nghostty-wall edit night colors.palette.0 101a45\nghostty-wall edit night colors.foreground auto')+'<p>The visual editor tracks Automatic and Customized colors per slot. Replacing the wallpaper recalculates only Automatic slots; Customized colors stay until reset. The advanced FIELD VALUE form saves immediately without applying. Version 2 Intent stores overrides; customizing legacy generated colors upgrades the saved Profile, not its historical Environments.</p><p>Background, foreground, palette.0–15, cursor, selection_background and selection_foreground support exact lowercase RGB hex or auto. Manual choices can reduce contrast; the editor keeps its controls readable independently of draft colors. Omitted colors stay unmanaged until explicitly enabled.</p>')+
 section('theme','Use a Ghostty theme',code('[colors]\nmode = "theme"\ntheme = "TokyoNight"','Profile · named theme','toml')+'<p>The theme must be available locally when the profile is resolved. Its colors are stored in the environment, so replay does not need the original theme file.</p>')+
 section('explicit','Set an explicit palette',code('''[colors]
mode = "explicit"
background = "1a1b26"
foreground = "c0caf5"
palette = [
  "15161e", "f7768e", "9ece6a", "e0af68",
  "7aa2f7", "bb9af7", "7dcfff", "a9b1d6",
  "414868", "f7768e", "9ece6a", "e0af68",
  "7aa2f7", "bb9af7", "7dcfff", "c0caf5",
]
cursor = "c0caf5"
selection_background = "33467c"
selection_foreground = "c0caf5"''','Profile · explicit colors','toml')+'<p>Provide a background, a foreground, and exactly 16 palette colors. Values are six lowercase hexadecimal digits without a <code>#</code>. Cursor and selection colors are optional.</p>')+
 section('readability','Keep your terminal readable','<p>Reduce <code>wallpaper.opacity</code> for bright images. Ghostty also supports <code>minimum-contrast = 4.5</code> in its normal root configuration.</p>'+note('<code>minimum-contrast</code> belongs in your normal Ghostty config, not a Ghostty Wall profile. Omit <code>[colors]</code> entirely to leave colors unmanaged.')),
 [('generated','Generated colors'),('customize','Automatic / Customized'),('theme','Ghostty themes'),('explicit','Explicit palette'),('readability','Readability')])

page('terminal-browser','Profile management center','Create, Edit, Delete and Use from one full-screen keyboard interface. Selection is exploration, not activation.','Guides',
 code('ghostty-wall\n# Equivalent:\nghostty-wall tui')+
 section('controls','Find your way around', '<p>In an interactive terminal, keys act immediately: no Enter after each shortcut. First launch offers initialization; the main screen starts on Profiles.</p>'+table(['Key','Action'],[('<kbd>n</kbd>','Create: Generate or Image, review, Save, then Use now / Not now'),('<kbd>e</kbd>','Edit a visual draft; confirmed Save and use'),('<kbd>x</kbd>','Delete with default-Cancel confirmation and protected Welcome fallback'),('<kbd>a</kbd>','Use selected Profile and stay in the management center'),('<kbd>↑</kbd> / <kbd>↓</kbd>, <kbd>j</kbd> / <kbd>k</kbd>','Select and automatically preview without applying'),('<kbd>Tab</kbd>','Switch Profiles / Sources; Enter on a Source starts Profile creation'),('<kbd>p</kbd> / <kbd>Enter</kbd>','Enlarge/restore the sample on compact layouts; not required to preview'),('<kbd>?</kbd>','Actions: Sources, duplicate/rename, History, Previous, Doctor, updates and maintenance'),('<kbd>v</kbd>','Full result/error details'),('<kbd>q</kbd> / <kbd>Ctrl-C</kbd>','Quit')]))+
 section('previews','Automatic, read-only Profile preview','<p>The initial and every arrow-selected Profile preview automatically. In Ghostty, a bounded full-color image appears behind representative text using Kitty graphics. Managed fit, position, repeat, opacity and image alpha are composed with the matching resolved colors, including random Profiles. The sample shows foreground/background, all 16 ANSI colors, cursor and selection. It is approximate, not live Ghostty reload; it does not execute a shell or capture your terminal.</p><p>Wallpaper blending uses <strong>linear-light sRGB</strong>, preserving saved opacity and RGB values. This models Ghostty’s linear/linear-corrected blending (the Linux default), not an inferred effective setting. Native blending, Display P3 and user overrides can differ. Font, blur and desktop transparency are not simulated; synthetic 8×16-pixel cells make geometry approximate. Zero opacity hides the photo, and arbitrary low-contrast/transparent recipes cannot guarantee recognition.</p><p>Unmanaged colors use neutral illustrative colors. Omitted image settings are illustrated as cover/center/no-repeat/opacity 1.0, not discovered from Ghostty. An unmanaged wallpaper is unknown and not shown; explicitly disabled wallpaper is labelled separately. Unsupported graphics show a labelled color-cell fallback, not photographic proof. Missing/corrupt images and unavailable Sources show errors without disabling navigation; <kbd>v</kbd> explains limitations and errors.</p><p>Preparation runs off the input loop, with one running request and one replaceable pending selection. Obsolete results cannot replace the current pane; navigation and quit remain available while loading. Repainting does not resolve again; resize reuses the resolved image while local inputs are unchanged. Successful samples watch local Profile/config/selected-image/source-root metadata. Reselect to retry an error or refresh remote content. There is no persisted preview cache.</p><p>Browsing leaves saved Profiles, Projection and History unchanged and requests no reload. Only explicit <strong>Use</strong> activates the selected Profile. Save, Activation and best-effort reload are separate outcomes; reload success is not proof of visible change. The [active] marker comes from the latest Profile Activation (compact lists use <code>*</code>); History replay does not invent an active Profile.</p>')+
 section('small','Small terminals','<p>The management browser supports <strong>60×18</strong> and larger, with list and automatic sample visible together even when compact. No preview key is required; <kbd>p</kbd>/<kbd>Enter</kbd> can enlarge it. Long IDs are elided in the list and the selected ID appears in the header. Below this management minimum, resize guidance and Esc/Ctrl-C cancellation remain available. Create/Edit forms retain their separate <strong>40×12</strong> minimum and compact sample toggle.</p>')+
 section('forms','Forms stay inside the interface','<p>Creation, visual editing, nested image picking, direct import (<kbd>N</kbd>), Source-based creation (<kbd>m</kbd> or Enter on a Source), rename/duplicate (<kbd>r</kbd>/<kbd>d</kbd>) and deletion remain full-screen. The localized Downloads/Pictures picker supports arrows, Enter, d/p roots, /text search and path:/absolute/path. Esc returns without importing.</p><p>Input forms retain values after validation errors: Enter advances/submits the last field, Tab/Shift-Tab revisits fields, Ctrl-U clears, F1 shows full errors, and Esc/Ctrl-C/Ctrl-D cancels. Creation saves before optional Use now; visual editing requires confirmed Save and use. Advanced <kbd>f</kbd>/<kbd>c</kbd>/<kbd>t</kbd>/<kbd>w</kbd> field edits save immediately without applying. Deletion shows the exact prepared summary; only <kbd>y</kbd> confirms, while Enter/n/Esc/Ctrl-C/Ctrl-D declines. Protected Welcome, active fallback and image-ownership checks still apply.</p><p>Non-terminal input retains the legacy line-based browser (key then Enter); it is not a fallback within a full-screen session.</p>')+
 section('maintenance','Maintenance, reports and updates','<p>First-start initialization and all Actions stay full-screen: Source add/inspection (including GitHub ref/subdirectory fields), List, History, Settings, Plan JSON, Doctor, Previous, update check/install, initialization/dry-run/repair/Welcome, migration/dry-run and Uninstall. Source administration means add and inspect, not rename or remove. Reports scroll with arrows/PageUp/PageDown; Enter/Esc/q returns after completion and <kbd>v</kbd> revisits details. Captured reports are bounded to 4 MiB, with truncation disclosed.</p><p>Maintenance mutations require explicit <kbd>y</kbd>; Enter/n/Esc/Ctrl-C/Ctrl-D declines. Long jobs stream progress off the input thread. Esc can close a read-only view, but its work may finish in the background; another maintenance read-only job must wait for it. After a mutation starts, cancellation is unavailable until completion/recovery: wait rather than terminating the process. Uninstall preserves Intent/History and returns to the browser, with Initialize/Repair available.</p><p>Check and Install update are separate Actions using the <a href="/installation/#update">same safe updater as the CLI</a>. Progress, failures and recovery instructions stay in the report. After replacement, restart Ghostty Wall; the running process retains its old version. <kbd>i</kbd> opens the original wallpaper inside the interface using Ghostty graphics, with a text fallback elsewhere. This is not the Profile-opacity sample or live reload.</p>')+
 section('random','Random profiles',code('ghostty-wall tui --seed '+seed)+'<p>A random Profile gets an automatic session preview seed, reused by Use. Pass an explicit 64-hex seed to reproduce a selection; nonrandom Profiles do not receive one. External Source changes can still change resolution.</p>'),
 [('controls','Keyboard controls'),('previews','Automatic preview'),('small','Small layouts'),('forms','Contained forms'),('maintenance','Maintenance / reports'),('random','Random profiles')])

commands=[('create [PROFILE]','Guided id, generated wallpaper or image picker, complete Profile, then optional Use now.'),('edit [PROFILE]','Visual draft editor; select when omitted, then confirmed Save and use.'),('delete [PROFILE]','Select or name a Profile and confirm; active deletion commits Welcome first.'),('apply PROFILE','Apply a Profile and record an Activation before best-effort reload.'),('tui','Full-screen Create / Edit / Delete / Use. Also the default with no command.'),('preview PROFILE','Read-only wallpaper, colors and terminal options; not live reload.'),('list','List Profiles.'),('history','Inspect committed Activations without changing state.'),('previous','Replay an earlier saved Environment without resolving original Sources.'),('new PROFILE IMAGE [--apply]','Copy a decoded PNG/JPEG into owned storage, with generated colors.'),('new PROFILE --generate SEED_HEX','Save a stable generated PNG and its recipe.'),('new PROFILE --source SOURCE --path CANDIDATE [--apply]','Create a Profile from an existing Source.'),('source add SOURCE local DIRECTORY','Register a local wallpaper directory.'),('source add SOURCE github OWNER/REPO [--ref REF] [--path PATH]','Register a GitHub Source.'),('edit PROFILE FIELD VALUE','Advanced immediate field save; does not apply.'),('duplicate PROFILE NEW','Copy Profile Intent without changing History.'),('rename PROFILE NEW','Rename an inactive, non-Welcome Profile.'),('init','Initialize managed layout, Welcome and the integration hook.'),('init --dry-run','Preview initialization without writes.'),('init --repair','Conservatively repair managed layout and integration.'),('init --welcome','Seed Welcome only in an eligible empty installation.'),('init --migrate-legacy','Import recognized Bash v0 configuration; supports --dry-run.'),('doctor','Read-only installation, integration and durable-state checks.'),('update --check','Fetch latest stable release metadata without installing or changing user data.'),('update','Verify and update a curl-managed installation.'),('uninstall','Remove integration and disposable state; preserve Profiles and History.'),('--help','Show usage; create/edit/delete/tui also provide command help.'),('--version','Show installed program version.')]
page('commands','Command reference','Every command, at a glance. All commands start with ghostty-wall.','Reference',
 section('commands','The complete command set',table(['Command','What it does'],[(f'<code>ghostty-wall {escape(c)}</code>',d) for c,d in commands]))+
 section('flags','Useful flags',table(['Flag','Use'],[('<code>--seed HEX</code>','Use with <code>plan</code>, <code>apply</code>, and <code>tui</code> for random-selection profiles.'),('<code>plan PROFILE --json</code>','Compact machine-readable JSON. Errors also use structured JSON and a nonzero exit code.'),('<code>init --migrate-legacy --dry-run</code>','Inspect a legacy migration before making changes.')]))+
 section('choices','Readable standalone choices','<p>Inline prompts separate headings, options, warnings, errors and input questions. Type a displayed key/number, then Enter. Defaults are explicit: after Save, Enter means Not now; deletion defaults to Cancel. Invalid choices can be corrected without authorizing a destructive action. Long labels and paths wrap with indented continuations.</p><p>Semantic colors require terminal input and output and a nonempty, non-dumb TERM. Any <code>NO_COLOR</code> value, including empty, disables styling. Non-TTY interaction stays plain. Machine-readable <code>plan --json</code> remains plain JSON without presentation escapes; exit codes and stdout/stderr routing are unchanged. Full-screen forms use their own controls.</p>')+
 section('examples','An everyday workflow',code('ghostty-wall create night\nghostty-wall edit night\nghostty-wall preview night\nghostty-wall apply night\nghostty-wall history\nghostty-wall previous\nghostty-wall doctor'))+
 note('There is no <code>next</code>, direct <code>random</code>/<code>set</code>, scheduler or destructive purge command. Internal previews do not activate or live-reload Ghostty.','Scope'),
 [('commands','All commands'),('flags','Useful flags'),('choices','CLI choices'),('examples','Examples')])

page('configuration','Configuration reference','Manage the settings you care about. Leave everything else in your normal Ghostty configuration.','Reference',
 section('files','Know your files',table(['File or directory','Purpose'],[('<code>config.toml</code>','Source definitions and schema version.'),('<code>profiles/*.toml</code>','Flat Profile Intent; version 1 stays readable, new owned-image Profiles use version 2.'),('<code>profiles/*.png / *.jpg</code>','Owned imported/generated images; never assume every image is safe to delete.'),('<code>environments/</code>','Immutable Environment snapshots referenced by History.'),('<code>current.ghostty</code>','Generated managed configuration; do not edit directly.'),('<code>history/activations/</code>','Durable activation history; preserve it.'),('<code>assets/sha256/</code>','Saved image assets; preserve them.'),('<code>cache/</code>','Disposable cache.')]))+
 section('editing','Prefer the visual editor',code('ghostty-wall edit night\n# Advanced: save one field immediately, without applying\nghostty-wall edit night terminal.font_size 14.5')+'<p>The visual editor groups Wallpaper, Colors and Terminal, with incremental controls and exact values. Schema version 2 additionally stores owned-image and generation metadata plus per-color overrides. Do not invent ownership claims or edit durable History by hand.</p>')+
 section('terminal','Terminal settings',code('''[terminal]
font_size = 13.5
background_opacity = 0.92
background_blur_intensity = 20
cursor_style = "bar"''','Profile · terminal','toml')+table(['Property','Accepted values'],[('<code>font_size</code>','1–1000, up to 3 decimal places.'),('<code>background_opacity</code>','0–1, up to 6 decimal places.'),('<code>background_blur_intensity</code>','Integer from 0–255.'),('<code>cursor_style</code>','<code>block</code>, <code>bar</code>, <code>underline</code>, <code>block_hollow</code>.')])+'<p>An empty <code>[terminal]</code> section is invalid. Omit the section when you do not want to manage any terminal settings.</p>')+
 section('opacity','Two different opacity settings','<p><code>background_opacity</code> controls the terminal background. <code>wallpaper.opacity</code> controls how the image is mixed in. Configure them independently.</p>')+
 section('unmanaged','What stays unmanaged','<p>Omitted fields are unmanaged. Font family, keybindings, minimum contrast, and other Ghostty settings remain in your normal Ghostty configuration.</p><p>Ghostty Wall manages selected visual settings through its integration hook; it does not replace your entire Ghostty config.</p>'),
 [('files','Files and directories'),('editing','Editing settings'),('terminal','Terminal settings'),('opacity','Opacity'),('unmanaged','Unmanaged settings')])

page('troubleshooting','Maintenance & recovery','Check your setup, repair the integration, and keep your profiles and history safe.','Reference',
 section('doctor','Check your installation',code('ghostty-wall doctor')+'<p>The doctor runs read-only checks and reports results as verified, failed, or unavailable.</p><p>If an install or update still shows an older version, check for a <a href="/installation/#path-conflicts">different executable earlier in PATH</a>.</p>')+
 section('reload','My terminal did not change','<p>Browsing and visual editing use internal samples: they do not live-reload Ghostty. Confirm Save and use, choose Use, or run apply to commit an Activation and attempt reload. Reload failure or unavailability does not undo committed History.</p><p>Check the config-file hook and Doctor output, then reload Ghostty manually if necessary. On Linux, the adapter uses the active systemd user service or running GTK application’s D-Bus action. Accepted commands do not prove visible change or affected-window scope.</p>'+note('The Linux live draft-session API is library-only, not wired into create/edit/TUI. Real-window draft change and cancel restoration remain unverified; macOS and restart-only settings remain experimental.','Live preview limitation'))+
 section('save-errors','Save failures and uncertainty','<p>If saving reports pre-save files preserved, correct the reported cause and retry the retained draft. A concurrent Intent/Source change requires reopening and reviewing it; do not overwrite it blindly. Publication uncertainty or incomplete rollback means files may remain: inspect the reported paths before retrying. A later apply failure can leave a successfully saved Profile.</p>')+
 section('deletion','Deletion refuses or keeps an image','<p>Welcome is protected. Active deletion requires an existing, valid Welcome fallback; older customized installs are not silently changed. Shared, reused or ambiguous images and History assets are retained intentionally. Changed confirmation targets require fresh confirmation, not forced removal.</p>')+
 section('performance','Local development seems slow','<p>For contributors testing a checkout: image decoding and complete History validation are expensive without optimization. Run the current release build instead of an old installed binary:</p>'+code('cargo run --locked --release -- tui'))+
 section('repair','Repair the integration',code('ghostty-wall init --repair')+'<p>This performs conservative layout and integration-hook repair. It cannot recreate lost profiles, images, environments, or history.</p>')+
 section('migration','Migrate from Bash v0',code('ghostty-wall init --migrate-legacy --dry-run\nghostty-wall init --migrate-legacy')+f'<p>Migration preserves legacy files and imports recognized sources. It cannot infer profiles: review the imported sources and create your profiles afterward. The previous Bash version remains at the <a href="{REPO}/tree/v0.2.2">v0.2.2 tag</a>.</p>')+
 section('uninstall','Uninstall',code('ghostty-wall uninstall')+'<p>This removes the integration hook and generated projection/cache. Your profiles, environments, assets, and history are preserved. Remove the binary separately using the installation method you originally used.</p>'+note('Only <code>cache/</code> is disposable. Images and activation history are durable data, not cache.','Keep your saved environments'))+
 section('help','Still need a hand?',f'<p><a href="{REPO}/issues">Open a GitHub issue</a> with the command you ran, your operating system, and the relevant error or doctor output.</p>'),
 [('doctor','Run the doctor'),('reload','Reload / live preview'),('save-errors','Save errors'),('deletion','Deletion safety'),('performance','Development builds'),('repair','Repair'),('migration','Migrate from v0'),('uninstall','Uninstall'),('help','Get help')])

nav=[('Get started',[('overview','Introduction','book'),('installation','Installation','download'),('quick-start','Quick start','bolt')]),('Guides',[('profiles','Profiles','layers'),('wallpapers','Wallpaper sources','image'),('colors','Colors & themes','palette'),('terminal-browser','Management center','terminal')]),('Reference',[('commands','Commands','code'),('configuration','Configuration','settings'),('troubleshooting','Maintenance & recovery','life')])]
nav_flat=[(k,t) for _,entries in nav for k,t,_ in entries]
for key,p in pages.items():
    navigation=''.join(f'<div class="nav-group"><p>{group}</p>'+''.join(f'<a href="{path(k)}" class="nav-item {"active" if k==key else ""}" '+('aria-current="page"' if k==key else '')+f'>{icon(i)}<span>{title}</span></a>' for k,title,i in entries)+'</div>' for group,entries in nav)
    toc=''.join(f'<a href="#{id}">{title}</a>' for id,title in p['toc'])
    idx=[k for k,t in nav_flat].index(key)
    prev=nav_flat[idx-1] if idx>0 else None
    nxt=nav_flat[idx+1] if idx+1<len(nav_flat) else None
    pagination='<nav class="pagination" aria-label="Documentation pages">'
    pagination+=f'<a href="{path(prev[0])}"><small>Previous</small><span>← {prev[1]}</span></a>' if prev else '<div></div>'
    pagination+=f'<a href="{path(nxt[0])}" class="next"><small>Up next</small><span>{nxt[1]} →</span></a>' if nxt else '<div></div>'
    pagination+='</nav>'
    plain_title=p['title'].replace('<br>',' ').replace('<em>','').replace('</em>','')
    title='Introduction' if key=='overview' else plain_title
    intro_title=p['title']
    html=f'''<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0d132b"><meta name="description" content="{escape(p['desc'].replace('<br>',' '),quote=True)}"><title>{title} — Ghostty Wall</title><link rel="icon" type="image/png" href="/assets/mascot.png"><link rel="stylesheet" href="/styles.css"><script src="/app.js" defer></script><script src="/release.js" defer></script></head>
<body class="{key}"><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><a class="brand" href="/" aria-label="Ghostty Wall home"><img src="/assets/mascot.png" alt="" width="36" height="36"><span>ghostty<span class="brand-dash">—</span>wall</span></a><span class="header-divider"></span><a class="header-docs" href="/">Documentation</a><div class="header-links"><a class="changelog" href="{REPO}/blob/main/CHANGELOG.md">Changelog {icon('arrow')}</a><a class="github-link" href="{REPO}">{icon('github')}<span>GitHub</span>{icon('arrow')}</a><button class="mobile-menu" type="button" aria-label="Open navigation" aria-expanded="false" aria-controls="sidebar">{icon('menu')}</button></div></header>
<aside class="sidebar" id="sidebar"><a class="version-pill" href="{REPO}/releases/latest" title="Open the latest stable release on GitHub"><span data-release-version aria-live="polite">Latest</span><small>Stable release</small>{icon('arrow')}</a><nav aria-label="Documentation">{navigation}</nav><div class="sidebar-bottom"><div class="open-source-label">{icon('heart')} Made for your terminal.</div><a href="{REPO}">Open source. Yours to make your own. {icon('arrow')}</a></div></aside><button class="drawer-backdrop" aria-label="Close navigation" tabindex="-1"></button>
<div class="content-layout"><main id="main" tabindex="-1"><div class="breadcrumb"><a href="/">Docs</a>{icon('chevron')}<span>{title}</span></div><div class="page-heading"><p class="eyebrow">{p['group']}</p><h1>{intro_title}</h1><p class="lead">{p['desc']}</p></div>{p['body']}{pagination}<footer class="page-footer"><span>Ghostty Wall {VERSION} · MIT License</span><a href="{REPO}/blob/main/README.md">Read the README {icon('arrow')}</a></footer></main><aside class="toc"><p>ON THIS PAGE</p><nav aria-label="On this page">{toc}</nav><div class="toc-help"><span>Building something good?</span><a href="{REPO}">Star us on GitHub {icon('arrow')}</a></div></aside></div><div id="copy-status" role="status" aria-live="polite"></div></body></html>'''
    target=OUT/'index.html' if key=='overview' else OUT/key/'index.html'
    target.parent.mkdir(exist_ok=True,parents=True)
    # Relative URLs work on both GitHub project Pages and local servers.
    prefix='./' if key=='overview' else '../'
    html=html.replace('href="/', f'href="{prefix}').replace('src="/', f'src="{prefix}')
    target.write_text(html)
print(f'Wrote {len(pages)} documentation pages.')
